api = "0.2"

[buildpack]
id = "org.cloudfoundry.yarn"
name = "Yarn Buildpack"
version = "{{ .Version }}"

[metadata]
include_files = ["bin/build","bin/detect","buildpack.toml"]
pre_package = "./scripts/build.sh"

[metadata.default_versions]
yarn = "1.19.0"

[[metadata.dependencies]]
id = "yarn"
name = "Yarn"
sha256 = "34293da6266f2aae9690d59c2d764056053ff7eebc56b80b8df05010c3da9343"
source = "https://github.com/yarnpkg/yarn/releases/download/v1.19.1/yarn-v1.19.1.tar.gz"
source_sha256 = "34293da6266f2aae9690d59c2d764056053ff7eebc56b80b8df05010c3da9343"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/yarn/yarn-1.19.1-any-stack-34293da6.tar.gz"
version = "1.19.1"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
id = "io.buildpacks.stacks.bionic"
