api = "0.2"

[buildpack]
  id = "org.cloudfoundry.yarn"
  name = "Yarn Buildpack"
  version = "{{ .Version }}"

[metadata]
  include_files = ["bin/build", "bin/detect", "buildpack.toml"]
  pre_package = "./scripts/build.sh"
  [metadata.default_versions]
    yarn = "1.19.*"

  [[metadata.dependencies]]
    id = "yarn"
    name = "Yarn"
    sha256 = "34293da6266f2aae9690d59c2d764056053ff7eebc56b80b8df05010c3da9343"
    source = "https://github.com/yarnpkg/yarn/releases/download/v1.19.1/yarn-v1.19.1.tar.gz"
    source_sha256 = "34293da6266f2aae9690d59c2d764056053ff7eebc56b80b8df05010c3da9343"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/yarn/yarn-1.19.1-any-stack-34293da6.tar.gz"
    version = "1.19.1"

  [[metadata.dependencies]]
    id = "yarn"
    name = "Yarn"
    sha256 = "2ed90e6aaf3988df5c75b6829b7c523754453a0b7134a9d0bf11161f927eae25"
    source = "https://github.com/yarnpkg/yarn/releases/download/v1.19.2/yarn-v1.19.2.tar.gz"
    source_sha256 = "2ed90e6aaf3988df5c75b6829b7c523754453a0b7134a9d0bf11161f927eae25"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/yarn/yarn-1.19.2-any-stack-2ed90e6a.tar.gz"
    version = "1.19.2"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"
