
[buildpack]
id = "org.cloudfoundry.buildpacks.yarn"
name = "Yarn Buildpack"
version = "0.0.2"

[[metadata.dependencies]]
id = "yarn"
name = "Yarn"
sha256 = "c63f402bcbf7499f015fe50f05f8b8d5f63fab08a10e4f78eb440baf54aac167"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2","org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/yarn/yarn-1.15.1-any-stack-c63f402b.tar.gz"
version = "1.15.1"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs2"

[[stacks]]
id = "io.buildpacks.stacks.bionic"
