api = "0.2"

[buildpack]
id = "org.cloudfoundry.yarn"
name = "Yarn Buildpack"
version = "{{ .Version }}"

[metadata]
include_files = ["bin/build","bin/detect","buildpack.toml"]
pre_package = "./scripts/build.sh"

[metadata.default_versions]
yarn = "1.16.0"

[[metadata.dependencies]]
id = "yarn"
name = "Yarn"
sha256 = "2f8d93c217ecca06eb720794c8d1484a67d37bdb58ab761108b5c651d59d3fc6"
source = "https://github.com/yarnpkg/yarn/releases/download/v1.18.0/yarn-v1.18.0.tar.gz"
source_sha256 = "2f8d93c217ecca06eb720794c8d1484a67d37bdb58ab761108b5c651d59d3fc6"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/yarn/yarn-1.18.0-any-stack-2f8d93c2.tar.gz"
version = "1.18.0"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
id = "io.buildpacks.stacks.bionic"
