
[buildpack]
id = "org.cloudfoundry.yarn"
name = "Yarn Buildpack"
version = "{{ .Version }}"

[metadata]
include_files = ["bin/build","bin/detect","buildpack.toml"]
pre_package = "./scripts/build.sh"

[metadata.default_versions]
yarn = "1.16.0"

[[metadata.dependencies]]
id = "yarn"
name = "Yarn"
sha256 = "e3835194409f1b3afa1c62ca82f561f1c29d26580c9e220c36866317e043c6f3"
source = "https://github.com/yarnpkg/yarn/releases/download/v1.17.3/yarn-v1.17.3.tar.gz"
source_sha256 = "e3835194409f1b3afa1c62ca82f561f1c29d26580c9e220c36866317e043c6f3"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/yarn/yarn-1.17.3-any-stack-e3835194.tar.gz"
version = "1.17.3"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
id = "io.buildpacks.stacks.bionic"
